# Welcome to Jekyll!
## This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LINTJ
email: contact@lintj.com
author:      T.J.  LIN
description: >- # this means to ignore newlines until "baseurl:"
  This is a beta version and this website is still under construction.
  Outages could happen suddenly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lintj.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: N/A
github_username:  gclintj

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/#   - vendor/ruby/


# Site settings
# title:       LINTJ
# email:       
# author:      T.J.  LIN
# description: "This is a beta version and this website is still under construction.
# Outages could happen suddenly.
# LINTJCOM
# lintjcom "
# baseurl:     ""
# exclude:     ['README.md']
# url:         "http://lintj.com"

timezone: America/Phoenix

# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC81MjgyMy8yOTMwMQ==

# Set the image for the Open Graph Protocol
image:
  path: /bbrb.ico
  height: 32
  width: 32
  
